repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8.5
-   repo: https://github.com/pycqa/flake8 #https://github.com/pre-commit/pre-commit-hooks
    rev: 3.9.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]


